# Generated by Django 3.2.4 on 2023-02-21 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='csv',
            name='DATE',
        ),
        migrations.AlterField(
            model_name='csv',
            name='CLOSE',
            field=models.CharField(max_length=20),
        ),
    ]
