# Generated by Django 3.2.4 on 2023-02-21 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0002_auto_20230220_1602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='csv',
            name='TIME',
        ),
        migrations.AlterField(
            model_name='csv',
            name='HIGH',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='csv',
            name='LOW',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='csv',
            name='OPEN',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='csv',
            name='VOLUME',
            field=models.CharField(max_length=20),
        ),
    ]
